<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://endpoint.ws.zafin.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://endpoint.ws.zafin.com/"
	name="HelloWorldImplService">
	<types />
	<message name="getHelloWorldAsString">
		<part name="arg0" type="xsd:string" />
	</message>
	<message name="getHelloWorldAsStringResponse">
		<part name="return" type="xsd:string" />
	</message>
	<portType name="HelloWorld">
		<operation name="getHelloWorldAsString">
			<input
				wsam:Action="http://endpoint.ws.zafin.com/HelloWorld/getHelloWorldAsStringRequest"
				message="tns:getHelloWorldAsString" />
			<output
				wsam:Action="http://endpoint.ws.zafin.com/HelloWorld/getHelloWorldAsStringResponse"
				message="tns:getHelloWorldAsStringResponse" />
		</operation>
	</portType>
	<binding name="HelloWorldImplPortBinding" type="tns:HelloWorld">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="rpc" />
		<operation name="getHelloWorldAsString">
			<soap:operation soapAction="" />
			<input>
				<soap:body use="literal" namespace="http://endpoint.ws.zafin.com/" />
			</input>
			<output>
				<soap:body use="literal" namespace="http://endpoint.ws.zafin.com/" />
			</output>
		</operation>
	</binding>
	<service name="HelloWorldImplService">
		<port name="HelloWorldImplPort" binding="tns:HelloWorldImplPortBinding">
			<soap:address location="http://localhost:9999/mockWB" />
		</port>
	</service>
</definitions>