package com.zafin;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-12-07T17:16:57.795-05:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://zafin.com", name = "SOATestEndpoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SOATestEndpoint {

    @WebMethod(operationName = "SOATest", action = "http://zafin.com")
    @WebResult(name = "outputSOATest", targetNamespace = "http://zafin.com", partName = "out")
    public OutputSOATest soaTest(
        @WebParam(partName = "in", name = "inputSOATest", targetNamespace = "http://zafin.com")
        InputSOATest in
    );
}
